# =Enhancements Configurations= #
#----------------------------------#

# Moshpit #

# Name of the Moshpit world.
moshpit-world: "hs_moshpit"

# Distance from the world spawn where damage and certain events are canceled (integer).
spawn-distance: 19

# Cooridinates between which the region of spawn is defined [x1, y1, z1, x2, y2, z2].
spawn-region: [988, 83, 1012, 1011, 74, 1035]

# Time delay between a player respawning and leaving the spawn radius in seconds (integer).
respawn-delay: 5

# Health gained from soup consumption (integer).
soup-regen: 12

# Time delay between soup consumption and regeneration in seconds (integer).
soup-delay: 25

# Max player health (double).
max-health: 40.0

# Allows players to gain coins through killing others (boolean).
coins-enabled: true

# The amount of coins gained per kill (integer).
coins-per-kill: 1

# Sets coins gained equal to the player's streak added to coins-per-kill (boolean). 
coin-stacking-enabled: true

#----------------------------------#

# Minigames #

#----------------------------------#

# Environment #

# General environmental damage modifier (double). 
modifier: 1.5

# List of worlds where the damage modifier is not enabled.
exempted-worlds: ["example_world", "example_world_1"]

# List of damage events not modified by the general modifier.
exempted-causes: [ENTITY_ATTACK, ENTITY_EXPLOSION]

#----------------------------------#